### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by mosynaq** [stav/scrapybox#1]
Hi! Sorry to ask such question: I have no clue how I can run this. How can I do so?
Thanks!

**Comment by stav** [comment]
Not the fastest turn-around time ever; but, I updated the [README](https://github.com/stav/scrapybox#installation) file with install instructions. Thanks for the prompt @mosynaq.

You can also just demo it with:

    pip install scrapybox
    pip install scrapy
    python -m scrapybox.server.server
